
package br.com.ggdio.estoque.services.autoresservice.v1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.com.ggdio.estoque.domain.v1.Autor;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutoresService", targetNamespace = "http://ggdio.com.br/estoque/services/AutoresService/v1")
@XmlSeeAlso({
    br.com.ggdio.estoque.domain.v1.ObjectFactory.class,
    br.com.ggdio.estoque.services.autoresservice.v1.ObjectFactory.class,
    br.com.ggdio.usuarios.domain.v1.ObjectFactory.class
})
public interface AutoresService {


    /**
     * 
     * @return
     *     returns java.util.List<br.com.ggdio.estoque.domain.v1.Autor>
     */
    @WebMethod(action = "AutoresService/listarAutores")
    @WebResult(name = "autor", targetNamespace = "")
    @RequestWrapper(localName = "listarAutores", targetNamespace = "http://ggdio.com.br/estoque/services/AutoresService/v1", className = "br.com.ggdio.estoque.services.autoresservice.v1.ListarAutores")
    @ResponseWrapper(localName = "listarAutoresResponse", targetNamespace = "http://ggdio.com.br/estoque/services/AutoresService/v1", className = "br.com.ggdio.estoque.services.autoresservice.v1.ListarAutoresResponse")
    public List<Autor> listarAutores();

}
