//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.28 at 09:47:28 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ggdio.com.br/estoque/domain/v1")
package br.com.ggdio.estoque.domain.v1;
